/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuProfessor.java
 *
 * Created on 08/07/2009, 11:21:16
 */
package interfaceGraficaUsuario;

import controle.BD;
import controle.DadosUsuarioEnum;
import controle.UsuariosEnum;
import java.util.List;

/**
 *
 * @author João Paulo
 */
public class MenuProfessor extends javax.swing.JFrame {

    private List<String> dadosUsuario;
    private static MenuProfessor janelaProfessor = new MenuProfessor();

    /** Creates new form MenuProfessor */
    public MenuProfessor() {
        initComponents();
//        janelaProfessor.setVisible(false);
    }

    public MenuProfessor(List<String> dadosUsuario) {
        this.dadosUsuario = dadosUsuario;
        initComponents();
        painelExibir.setVisible(false);
        painelExibir.setText("");

        labelSaudacao.setText("Olá, " + dadosUsuario.get(DadosUsuarioEnum.NOME.ordinal()) + ". email: " + dadosUsuario.get(DadosUsuarioEnum.EMAIL.ordinal()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSaudacao = new javax.swing.JLabel();
        painelDeAbas = new javax.swing.JTabbedPane();
        abaPainelAvisos = new javax.swing.JTabbedPane();
        abaPainelPlanoDeAula = new javax.swing.JTabbedPane();
        abaPainelCriterio = new javax.swing.JTabbedPane();
        abaPainelInfoProjeto = new javax.swing.JTabbedPane();
        abaPainelNotas = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelExibir = new javax.swing.JTextPane();
        menuBarProfessor = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuAdicionar = new javax.swing.JMenu();
        addAluno = new javax.swing.JMenuItem();
        addMonitor = new javax.swing.JMenuItem();
        addExercicio = new javax.swing.JMenuItem();
        menuRemover = new javax.swing.JMenu();
        removerAluno = new javax.swing.JMenuItem();
        removerMonitor = new javax.swing.JMenuItem();
        removerExercicio = new javax.swing.JMenuItem();
        menuResetarBD = new javax.swing.JMenu();
        resetarAlunos = new javax.swing.JMenuItem();
        resetarSubmissões = new javax.swing.JMenuItem();
        resetarExercicios = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        menuEditarDados = new javax.swing.JMenuItem();
        menuAlterarSenha = new javax.swing.JMenuItem();
        editarExercicio = new javax.swing.JMenuItem();
        menuExibir = new javax.swing.JMenu();
        exibirAlunos = new javax.swing.JMenuItem();
        exibirMonitores = new javax.swing.JMenuItem();
        exibirExercicios = new javax.swing.JMenuItem();
        exibirPlanilha = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        ajudaHelp = new javax.swing.JMenuItem();
        ajudaSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        labelSaudacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        painelDeAbas.addTab("Avisos", abaPainelAvisos);
        painelDeAbas.addTab("Plano de Aula", abaPainelPlanoDeAula);
        painelDeAbas.addTab("Critério de Avaliação", abaPainelCriterio);
        painelDeAbas.addTab("Informações do Projeto", abaPainelInfoProjeto);
        painelDeAbas.addTab("Notas", abaPainelNotas);

        painelExibir.setBackground(new java.awt.Color(240, 240, 240));
        jScrollPane1.setViewportView(painelExibir);

        menuArquivo.setText("Arquivo");

        menuAdicionar.setText("Adicionar");

        addAluno.setText("Aluno");
        addAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlunoActionPerformed(evt);
            }
        });
        menuAdicionar.add(addAluno);

        addMonitor.setText("Monitor");
        addMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMonitorActionPerformed(evt);
            }
        });
        menuAdicionar.add(addMonitor);

        addExercicio.setText("Exercício");
        menuAdicionar.add(addExercicio);

        menuArquivo.add(menuAdicionar);

        menuRemover.setText("Remover");

        removerAluno.setText("Aluno");
        menuRemover.add(removerAluno);

        removerMonitor.setText("Monitor");
        menuRemover.add(removerMonitor);

        removerExercicio.setText("Exercício");
        menuRemover.add(removerExercicio);

        menuArquivo.add(menuRemover);

        menuResetarBD.setText("Resetar BD");

        resetarAlunos.setText("Alunos");
        resetarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarAlunosActionPerformed(evt);
            }
        });
        menuResetarBD.add(resetarAlunos);

        resetarSubmissões.setText("Submissões");
        menuResetarBD.add(resetarSubmissões);

        resetarExercicios.setText("Exercícios");
        menuResetarBD.add(resetarExercicios);

        menuArquivo.add(menuResetarBD);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuSair);

        menuBarProfessor.add(menuArquivo);

        menuEditar.setText("Editar");

        menuEditarDados.setText("Editar Dados");
        menuEditar.add(menuEditarDados);

        menuAlterarSenha.setText("Alterar Senha");
        menuEditar.add(menuAlterarSenha);

        editarExercicio.setText("Editar Exercício");
        menuEditar.add(editarExercicio);

        menuBarProfessor.add(menuEditar);

        menuExibir.setText("Exibir");

        exibirAlunos.setText("Alunos");
        exibirAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirAlunosActionPerformed(evt);
            }
        });
        menuExibir.add(exibirAlunos);

        exibirMonitores.setText("Monitores");
        exibirMonitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirMonitoresActionPerformed(evt);
            }
        });
        menuExibir.add(exibirMonitores);

        exibirExercicios.setText("Exercícios");
        menuExibir.add(exibirExercicios);

        exibirPlanilha.setText("Planilha de Notas");
        menuExibir.add(exibirPlanilha);

        menuBarProfessor.add(menuExibir);

        menuAjuda.setText("Ajuda");

        ajudaHelp.setText("Help");
        menuAjuda.add(ajudaHelp);

        ajudaSobre.setText("Sobre");
        menuAjuda.add(ajudaSobre);

        menuBarProfessor.add(menuAjuda);

        setJMenuBar(menuBarProfessor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSaudacao, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(painelDeAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelSaudacao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelDeAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(47, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        janelaProfessor.setVisible(false);

}//GEN-LAST:event_menuSairMouseClicked

    private void addMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMonitorActionPerformed
        AdicionarUsuario addUser = new AdicionarUsuario(UsuariosEnum.MONITOR);
        addUser.setVisible(true);
    }//GEN-LAST:event_addMonitorActionPerformed

    private void addAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAlunoActionPerformed
        AdicionarUsuario addUser = new AdicionarUsuario(UsuariosEnum.ALUNO);
        addUser.setVisible(true);
    }//GEN-LAST:event_addAlunoActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);

    }//GEN-LAST:event_menuSairActionPerformed

    private void exibirAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirAlunosActionPerformed
        painelDeAbas.setVisible(false);
        painelExibir.setText(BD.listaDeAlunos());
        painelExibir.setVisible(true);
    }//GEN-LAST:event_exibirAlunosActionPerformed

    private void exibirMonitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirMonitoresActionPerformed
        painelDeAbas.setVisible(false);
        painelExibir.setText(BD.listaDeModeradores());
        painelExibir.setVisible(true);
    }//GEN-LAST:event_exibirMonitoresActionPerformed

    private void resetarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetarAlunosActionPerformed
        BD.resetAlunos();
    }//GEN-LAST:event_resetarAlunosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                janelaProfessor.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abaPainelAvisos;
    private javax.swing.JTabbedPane abaPainelCriterio;
    private javax.swing.JTabbedPane abaPainelInfoProjeto;
    private javax.swing.JTabbedPane abaPainelNotas;
    private javax.swing.JTabbedPane abaPainelPlanoDeAula;
    private javax.swing.JMenuItem addAluno;
    private javax.swing.JMenuItem addExercicio;
    private javax.swing.JMenuItem addMonitor;
    private javax.swing.JMenuItem ajudaHelp;
    private javax.swing.JMenuItem ajudaSobre;
    private javax.swing.JMenuItem editarExercicio;
    private javax.swing.JMenuItem exibirAlunos;
    private javax.swing.JMenuItem exibirExercicios;
    private javax.swing.JMenuItem exibirMonitores;
    private javax.swing.JMenuItem exibirPlanilha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSaudacao;
    private javax.swing.JMenu menuAdicionar;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem menuAlterarSenha;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBarProfessor;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenuItem menuEditarDados;
    private javax.swing.JMenu menuExibir;
    private javax.swing.JMenu menuRemover;
    private javax.swing.JMenu menuResetarBD;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JTabbedPane painelDeAbas;
    private javax.swing.JTextPane painelExibir;
    private javax.swing.JMenuItem removerAluno;
    private javax.swing.JMenuItem removerExercicio;
    private javax.swing.JMenuItem removerMonitor;
    private javax.swing.JMenuItem resetarAlunos;
    private javax.swing.JMenuItem resetarExercicios;
    private javax.swing.JMenuItem resetarSubmissões;
    // End of variables declaration//GEN-END:variables
}
