/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QuadroDeInformacoes.java
 *
 * Created on 13/07/2009, 14:32:00
 */
package interfaceGraficaUsuario;

import controle.UsuariosEnum;

/**
 *
 * @author João Paulo
 */
public class QuadroDeInformacoes extends javax.swing.JFrame {

    private static String avisos = "";
    private static String plano = "";
    private static String info = "";
    private static String criterios = "";

    /** Creates new form QuadroDeInformacoes */
    public QuadroDeInformacoes() {
        initComponents();        
        campoAvisos.setText(avisos);
        campoPlano.setText(plano);
        campoInfo.setText(info);
        campoCriterios.setText(criterios);
    }

    public javax.swing.JTabbedPane getPainel() {

        campoAvisos.setText(avisos);
        campoPlano.setText(plano);
        campoInfo.setText(info);
        campoCriterios.setText(criterios);
        return painelDeInformacoes;
    }

    public void salvarTextos() {
        avisos += campoAvisos.getText();
        plano += campoPlano.getText();
        info += campoInfo.getText();
        criterios += campoCriterios.getText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDeInformacoes = new javax.swing.JTabbedPane();
        painelAvisos = new javax.swing.JScrollPane();
        campoAvisos = new javax.swing.JTextArea();
        painelPlano = new javax.swing.JScrollPane();
        campoPlano = new javax.swing.JTextArea();
        painelCriterios = new javax.swing.JScrollPane();
        campoCriterios = new javax.swing.JTextPane();
        painelInfo = new javax.swing.JScrollPane();
        campoInfo = new javax.swing.JTextArea();
        botaoSalvar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        campoAvisos.setColumns(20);
        campoAvisos.setRows(5);
        painelAvisos.setViewportView(campoAvisos);

        painelDeInformacoes.addTab("Avisos", painelAvisos);

        campoPlano.setColumns(20);
        campoPlano.setRows(5);
        painelPlano.setViewportView(campoPlano);

        painelDeInformacoes.addTab("Plano de Aula", painelPlano);

        painelCriterios.setViewportView(campoCriterios);

        painelDeInformacoes.addTab("Critérios de Avaliação", painelCriterios);

        campoInfo.setColumns(20);
        campoInfo.setRows(5);
        painelInfo.setViewportView(campoInfo);

        painelDeInformacoes.addTab("Informações do Projeto", painelInfo);

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDeInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoSalvar)
                        .addGap(26, 26, 26)
                        .addComponent(botaoSair)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelDeInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoSair)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        dispose();
}//GEN-LAST:event_botaoSairActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        salvarTextos();
}//GEN-LAST:event_botaoSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new QuadroDeInformacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextArea campoAvisos;
    private javax.swing.JTextPane campoCriterios;
    private javax.swing.JTextArea campoInfo;
    private javax.swing.JTextArea campoPlano;
    private javax.swing.JScrollPane painelAvisos;
    private javax.swing.JScrollPane painelCriterios;
    private javax.swing.JTabbedPane painelDeInformacoes;
    private javax.swing.JScrollPane painelInfo;
    private javax.swing.JScrollPane painelPlano;
    // End of variables declaration//GEN-END:variables
}
