/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuAluno.java
 *
 * Created on 04/07/2009, 19:42:48
 */

package graphic;

import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.util.List;

import controle.DadosUsuarioEnum;
import controle.Sistema;

/**
 * 
 * @author Administrador
 */
public class MenuAluno extends javax.swing.JFrame {
	private String login;

	/** Creates new form MenuAluno */
	public MenuAluno() {
		initComponents();
	}

	public MenuAluno(String login) {
		this.login = login;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		// bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

		jPopupMenu1 = new javax.swing.JPopupMenu();
		jPanel1 = new javax.swing.JPanel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jTabbedPane2 = new javax.swing.JTabbedPane();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jTabbedPane3 = new javax.swing.JTabbedPane();
		jTabbedPane4 = new javax.swing.JTabbedPane();
		jTabbedPane5 = new javax.swing.JTabbedPane();
		jTabbedPane6 = new javax.swing.JTabbedPane();
		jLabel1 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		editarDados = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		jMenuItem9 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenu5 = new javax.swing.JMenu();
		jMenuItem7 = new javax.swing.JMenuItem();
		jMenuItem8 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null },
						{ null, null }, { null, null }, { null, null },
						{ null, null }, { null, null }, { null, null },
						{ null, null }, { null, null }, { null, null },
						{ null, null }, { null, null }, { null, null },
						{ null, null }, { null, null }, { null, null } },
				new String[] { "Dia", "Assunto" }));
		jScrollPane1.setViewportView(jTable1);

		// jTabbedPane2.addTab("tab1", jScrollPane1); //tirei a aba la.

		jTabbedPane1.addTab("Plano de Aula", jTabbedPane2);
		jTabbedPane1.addTab("Avisos", jTabbedPane3);
		jTabbedPane1.addTab("Critérios de Avaliação", jTabbedPane4);
		jTabbedPane1.addTab("Projeto", jTabbedPane5);
		jTabbedPane1.addTab("Notas", jTabbedPane6);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel1.setText("Olá, "
				+ dadosAlunos(login).get(DadosUsuarioEnum.NOME.ordinal())
				+ " email: "
				+ dadosAlunos(login).get(DadosUsuarioEnum.EMAIL.ordinal()));
		jLabel1.setAutoscrolls(true);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																386,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTabbedPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																406,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 39,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(
								18, 18, 18).addComponent(jTabbedPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 200,
								Short.MAX_VALUE).addContainerGap()));

		jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

		jMenu1.setText("Arquivo");

		// org.jdesktop.beansbinding.Binding binding =
		// org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
		// jPopupMenu1, org.jdesktop.beansbinding.ObjectProperty.create(),
		// jMenu1, org.jdesktop.beansbinding.BeanProperty.create("selected"));
		// bindingGroup.addBinding(binding);

		jMenuItem1.setText("Sair");
		jMenu1.add(jMenuItem1);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Editar");

		editarDados.setText("Dados Pessoais");
		jMenu2.add(editarDados);

		jMenuItem3.setText("Alterar Senha");
		jMenu2.add(jMenuItem3);

		jMenuBar1.add(jMenu2);

		jMenu4.setText("Exercicios");

		jMenuItem9.setText("Planilha de Notas");
		jMenu4.add(jMenuItem9);

		jMenuItem4.setText("Exibir Exercicios");
		jMenu4.add(jMenuItem4);

		jMenuItem5.setText("Exibir Meus Exercicios");
		jMenu4.add(jMenuItem5);

		jMenuItem6.setText("Enviar Exercicio");
		jMenu4.add(jMenuItem6);

		jMenuBar1.add(jMenu4);

		jMenu5.setText("Ajuda");

		jMenuItem7.setText("Help");
		jMenu5.add(jMenuItem7);

		jMenuItem8.setText("Sobre");
		jMenu5.add(jMenuItem8);

		jMenuBar1.add(jMenu5);

		setJMenuBar(jMenuBar1);

		editarDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarDadosMouseClicked(evt);
            }
        });
        editarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarDadosActionPerformed(evt);
            }
        });
        
//        editarDados.addKeyListener(new java.awt.event.KeyListener()) {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                editarDadosActionPerformed(evt);
//            }
//        });
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		// bindingGroup.bind();

		pack();
	}// </editor-fold>
	
	protected void editarDadosActionPerformed(ActionEvent evt) {
		EditaDados editarDados = new EditaDados(login);
		editarDados.setVisible(true);
		
	}

	private void editarDadosMouseClicked(java.awt.event.MouseEvent evt) {
		EditaDados editarDados = new EditaDados(login);
		editarDados.setVisible(true);
    }

	public static List<String> dadosAlunos(String login) {
		return Sistema.dadosUsuario(login);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MenuAluno().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem editarDados;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JMenuItem jMenuItem8;
	private javax.swing.JMenuItem jMenuItem9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPopupMenu jPopupMenu1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane2;
	private javax.swing.JTabbedPane jTabbedPane3;
	private javax.swing.JTabbedPane jTabbedPane4;
	private javax.swing.JTabbedPane jTabbedPane5;
	private javax.swing.JTabbedPane jTabbedPane6;
	private javax.swing.JTable jTable1;
	// private org.jdesktop.beansbinding.BindingGroup bindingGroup;
	// End of variables declaration

}


