/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuProfessor.java
 *
 * Created on 04/07/2009, 19:57:26
 */

package graphic;

import javax.swing.JOptionPane;

/**
 *
 * @author joao
 */
public class MenuProfessor extends javax.swing.JFrame {

    /** Creates new form MenuProfessor */
    public MenuProfessor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
//        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        profPainel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        profMenuBar = new javax.swing.JMenuBar();
        menuProfArquivo = new javax.swing.JMenu();
        menuProfNovo = new javax.swing.JMenu();
        menuProfNovoAluno = new javax.swing.JMenuItem();
        menuProfNovoMonitor = new javax.swing.JMenuItem();
        menuProfNovoExercicio = new javax.swing.JMenuItem();
        menuProfRemover = new javax.swing.JMenu();
        menuProfRemoverAluno = new javax.swing.JMenuItem();
        menuProfRemoverMonitor = new javax.swing.JMenuItem();
        menuProfRemoverEx = new javax.swing.JMenuItem();
        menuProfSair = new javax.swing.JMenuItem();
        menuProfEditar = new javax.swing.JMenu();
        menuProfEditarDados = new javax.swing.JMenuItem();
        menuProfEditarSenha = new javax.swing.JMenuItem();
        menuProfEditarExercicio = new javax.swing.JMenuItem();
        menuProfExibir = new javax.swing.JMenu();
        menuProfExibirAlunos = new javax.swing.JMenuItem();
        menuProfExibirMonitores = new javax.swing.JMenuItem();
        menuProfExibirExercicios = new javax.swing.JMenuItem();
        menuProfPlanilhaNotas = new javax.swing.JMenuItem();
        menuProfAjuda = new javax.swing.JMenu();
        menuProfHelp = new javax.swing.JMenuItem();
        menuProfSobre = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        profPainel1.setBackground(new java.awt.Color(255, 255, 255));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 0, 24));
        label1.setText("Laboratório de Programação 2 - 2009.1");

        javax.swing.GroupLayout profPainel1Layout = new javax.swing.GroupLayout(profPainel1);
        profPainel1.setLayout(profPainel1Layout);
        profPainel1Layout.setHorizontalGroup(
            profPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profPainel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );
        profPainel1Layout.setVerticalGroup(
            profPainel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profPainel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jLabel1.setText("jLabel1");

        profMenuBar.setBackground(new java.awt.Color(255, 255, 255));
        profMenuBar.setAutoscrolls(true);

        menuProfArquivo.setText("Arquivo");

        menuProfNovo.setText("Novo");

        menuProfNovoAluno.setText("Aluno");
        menuProfNovo.add(menuProfNovoAluno);

        menuProfNovoMonitor.setText("Monitor");
        menuProfNovo.add(menuProfNovoMonitor);

        menuProfNovoExercicio.setText("Exercício");
        menuProfNovo.add(menuProfNovoExercicio);

        menuProfArquivo.add(menuProfNovo);

        menuProfRemover.setText("Remover");

        menuProfRemoverAluno.setText("Aluno");
        menuProfRemover.add(menuProfRemoverAluno);

        menuProfRemoverMonitor.setText("Monitor");
        menuProfRemover.add(menuProfRemoverMonitor);

        menuProfRemoverEx.setText("Exercício");
        menuProfRemover.add(menuProfRemoverEx);

        menuProfArquivo.add(menuProfRemover);

        menuProfSair.setText("Sair");
        menuProfSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProfSairMouseClicked(evt);
            }
        });
        menuProfArquivo.add(menuProfSair);

        profMenuBar.add(menuProfArquivo);

        menuProfEditar.setText("Editar");

        menuProfEditarDados.setText("Dados Pessoais");

//        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, menuProfEditarDados, org.jdesktop.beansbinding.ObjectProperty.create(), menuProfEditarDados, org.jdesktop.beansbinding.BeanProperty.create("selected"));
//        bindingGroup.addBinding(binding);

        menuProfEditarDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProfEditarDadosMouseClicked(evt);
            }
        });
        menuProfEditar.add(menuProfEditarDados);

        menuProfEditarSenha.setText("Alterar Senha");
        menuProfEditar.add(menuProfEditarSenha);

        menuProfEditarExercicio.setText("Atualizar Exercicio");
        menuProfEditar.add(menuProfEditarExercicio);

        profMenuBar.add(menuProfEditar);

        menuProfExibir.setText("Exibir");

        menuProfExibirAlunos.setText("Alunos");
        menuProfExibir.add(menuProfExibirAlunos);

        menuProfExibirMonitores.setText("Monitores");
        menuProfExibir.add(menuProfExibirMonitores);

        menuProfExibirExercicios.setText("Exercícios");
        menuProfExibir.add(menuProfExibirExercicios);

        menuProfPlanilhaNotas.setText("Planilha de Notas");
        menuProfExibir.add(menuProfPlanilhaNotas);

        profMenuBar.add(menuProfExibir);

        menuProfAjuda.setText("Ajuda");

        menuProfHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuProfHelp.setText("Help");
        menuProfAjuda.add(menuProfHelp);

        menuProfSobre.setText("Sobre");
        menuProfAjuda.add(menuProfSobre);

        profMenuBar.add(menuProfAjuda);

        setJMenuBar(profMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profPainel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profPainel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

//        bindingGroup.bind();

        pack();
    }// </editor-fold>

    private void menuProfSairMouseClicked(java.awt.event.MouseEvent evt) {                                          
        System.exit(0);
    }                                         

    private void menuProfEditarDadosMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label1;
    private javax.swing.JMenu menuProfAjuda;
    private javax.swing.JMenu menuProfArquivo;
    private javax.swing.JMenu menuProfEditar;
    private javax.swing.JMenuItem menuProfEditarDados;
    private javax.swing.JMenuItem menuProfEditarExercicio;
    private javax.swing.JMenuItem menuProfEditarSenha;
    private javax.swing.JMenu menuProfExibir;
    private javax.swing.JMenuItem menuProfExibirAlunos;
    private javax.swing.JMenuItem menuProfExibirExercicios;
    private javax.swing.JMenuItem menuProfExibirMonitores;
    private javax.swing.JMenuItem menuProfHelp;
    private javax.swing.JMenu menuProfNovo;
    private javax.swing.JMenuItem menuProfNovoAluno;
    private javax.swing.JMenuItem menuProfNovoExercicio;
    private javax.swing.JMenuItem menuProfNovoMonitor;
    private javax.swing.JMenuItem menuProfPlanilhaNotas;
    private javax.swing.JMenu menuProfRemover;
    private javax.swing.JMenuItem menuProfRemoverAluno;
    private javax.swing.JMenuItem menuProfRemoverEx;
    private javax.swing.JMenuItem menuProfRemoverMonitor;
    private javax.swing.JMenuItem menuProfSair;
    private javax.swing.JMenuItem menuProfSobre;
    private javax.swing.JMenuBar profMenuBar;
    private javax.swing.JPanel profPainel1;
//    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration

}
